Update .gitmodules to work with fleximod
ESCOMP/HEMCO_CESM pull request #42
Opened 2024-12-04 21:37 UTC by lizziel

### Name and Institution (Required)

Name: Lizzie Lundgren
Institution: Harvard University

### Describe the update

This PR updates .gitmodules to use fleximod. Several of the required lines were omitted when first added.

### Expected changes

Fleximod will checkout the HEMCO tag specified in .gitmodules. Using git submodules will no longer be required to checkout  HEMCO version.

### Reference(s)

None

### Related Github Issue

None (?)

2024-12-11 15:41 UTC, lizziel commented
@jedwards4b, heads up I tagged you as reviewer for this PR. Let me know if you have any questions.

2024-12-11 16:10 UTC, jedwards4b requested changes
fxDONOTUSEurl should be https://github.com/geoschem/hemco.git
(the same as url) the purpose of this variable is to assure that commits to primary branches such as development do not include forks of the repository.   Using a fork will cause the cam
github workflow to give an error.

2024-12-12 14:39 UTC, lizziel commented
@jedwards4b, I am not sure what change you are requesting. fxDONOTUSEurl is already set to https://github.com/geoschem/hemco.git.

2024-12-12 14:46 UTC, jedwards4b approved these changes
I'm sorry - there was a line break in my window and I missed the rest of the line.  This looks good.

2024-12-16 14:36 UTC, merged